# Generated by Django 5.1.3 on 2024-11-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlueTick_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about_me", models.TextField()),
                ("phone", models.CharField(max_length=13)),
                ("telegram", models.URLField(blank=True, null=True)),
                ("instagram", models.URLField(blank=True, null=True)),
                ("whatsapp", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
