# Generated by Django 5.1.3 on 2024-11-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0002_bluetick_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="bluetick_info",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
