# Generated by Django 5.1.3 on 2024-11-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0003_bluetick_info_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ads_banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="adsBanner/"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="apps",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="apps/"),
        ),
        migrations.AlterField(
            model_name="bluetick_info",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="banner/"),
        ),
    ]
