# Generated by Django 5.1.3 on 2024-11-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0004_ads_banner_alter_apps_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ads_banner",
            name="image",
            field=models.ImageField(upload_to="adsBanner/"),
        ),
    ]
